import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

export const EVEROS_FCNTL_SHIM_FILE = 'fcntl.py';

/**
 * Windows 下给 EverOS 使用的 fcntl 兼容 shim 内容。
 *
 * EverOS 的 memory-root lock 依赖 `fcntl.flock`，该模块在 Windows 原生 Python
 * 中不存在。此 shim 将 `flock` 转发到 EverOS 已经依赖的 `portalocker`，从而
 * 在不修改 EverOS 源码的前提下支持 Windows。
 */
export function getFcntlShimContent(): string {
  return `"""Windows fcntl shim for EverOS.

EverOS uses fcntl.flock for its memory-root lock, which is not available on
Windows. This module provides a minimal compatibility layer backed by
portalocker (already a dependency of EverOS).

Do not edit this file manually: it is generated by CodeKeeper Advance at
runtime.
"""

import os

import portalocker

LOCK_SH = 1
LOCK_EX = 2
LOCK_NB = 4
LOCK_UN = 8


def flock(fd: int, operation: int) -> None:
    """Emulate fcntl.flock using portalocker."""
    if operation == 0:
        return

    flags = 0
    if operation & LOCK_EX:
        flags |= portalocker.LOCK_EX
    elif operation & LOCK_SH:
        flags |= portalocker.LOCK_SH
    if operation & LOCK_NB:
        flags |= portalocker.LOCK_NB
    if operation & LOCK_UN:
        flags |= portalocker.LOCK_UN

    # EverOS 拥有该文件描述符的生命周期，shim 不能关闭它。
    file_obj = os.fdopen(fd, "r+", closefd=False)
    try:
        portalocker.lock(file_obj, flags)
    except portalocker.LockException as exc:
        if operation & LOCK_NB:
            raise BlockingIOError("resource temporarily unavailable") from exc
        raise
`;
}

/**
 * 构造传递给 EverOS 子进程的环境变量。
 *
 * Windows 下会将 fcntl shim 目录加入 PYTHONPATH，其他平台保持原样。
 */
export function buildEverOSProcessEnv(
  platform: string,
  env: NodeJS.ProcessEnv,
  shimDir: string
): NodeJS.ProcessEnv {
  if (platform !== 'win32') return env;
  return {
    ...env,
    PYTHONPATH: buildWindowsPythonPath(shimDir, env.PYTHONPATH),
  };
}

/**
 * 将 fcntl shim 写入指定目录，返回写入后的完整文件路径。
 */
export async function ensureFcntlShim(shimDir: string): Promise<string> {
  await mkdir(shimDir, { recursive: true });
  const shimPath = join(shimDir, EVEROS_FCNTL_SHIM_FILE);
  await writeFile(shimPath, getFcntlShimContent(), 'utf-8');
  return shimPath;
}

/**
 * 构造 Windows 下的 PYTHONPATH，将 shim 目录置于最前。
 */
export function buildWindowsPythonPath(shimDir: string, existing?: string): string {
  if (!existing) return shimDir;
  return `${shimDir};${existing}`;
}
